services:
  postgres:
    image: postgres:16
    container_name: vault-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: secure_vault
      POSTGRES_USER: vault
      POSTGRES_PASSWORD: vault_password_change_me
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: vault-keycloak
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: vault
      KC_DB_PASSWORD: vault_password_change_me
      KC_DB_URL_DATABASE: secure_vault
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password_change_me
    command:
      - start-dev
      - --http-port=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
